### ISSUE TITLE
windows 下 lyx2.3 无法使用。

### ISSUE THREAD

**Issue by drongh** [cogenda/cgdrep#1]
在windows 下，把layout放在C:\Softwares\LyX 2.3\Resources\layouts下，cls文件放在C:\Softwares\LyX 2.3\Resources\tex 下，还是无法使用，请帮忙看看。

在Lyx软件下，菜单 `文档 -> 首选项 -> 文档类` 的 document class 中，显示 `不存在：report(Cogenda CN)`.

**Comment by hashhsah** [comment]
latex模板安装、使用正常么？

latex模板安装成功后，启动Lyx后，点击tools->reconfigure菜单项，让lyx能搜索到cgdrep等latex模板。

**Comment by drongh** [comment]
点了那个reconfigure了，还是没用。报错是缺少cls。没有cgdrep 模版。。

**Comment by hashhsah** [comment]
> 点了那个reconfigure了，还是没用。报错是缺少cls。没有cgdrep 模版。。

通常，这表示latex模板还没有安装好。需要先安装latex（比如miktex+ctex），确认安装正常，再安装lyx模板。

**Comment by hashhsah** [comment]
在lyx邮件列表里，有windows下有用户反映之前的一个lyx2.3打包有问题。直到3月16日lyx2.3才正式发布。请尝试一下。

如果没有进一步更新的话，我把这个issue关闭了。

**Comment by hashhsah** [comment]
没有进一步反馈。先关闭。

**Comment by QingyuGuo** [comment]
还是不行的啊
